# Site wide configuration
title: João Netto
description: "passionate web and mobile developer that loves new technologies"
logo: bio-photo.jpg # 120x120 px default image used for Twitter summary card
teaser: bio-photo.jpg # 400x250 px default teaser image used in image archive grid
locale: en_US
url: http://joaonetto.me

# Jekyll configuration

source: _source
sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments

# Site owner
owner:
  name: João Netto
  email: hi@joaonetto.me
  twitter: jnettome
  google:
    analytics: UA-19971072-1
    plus: 111092052554396666461
  bio: "full-stack web and mobile developer"
  avatar: bio-photo-byline.jpg # 80x80px
disqus-shortname: jnettome


include: [".htaccess"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
